### ISSUE TITLE
SeaHash

### ISSUE THREAD

**Issue by ticki** [flier/rust-fasthash#1]
https://docs.rs/seahash/3.0.5/seahash/

**Comment by flier** [comment]
Great, I have added a wrapper about your [SeaHash](https://github.com/flier/rust-fasthash/commit/6e7cc7b731e7ad02e2332139018e8dfd1d52ba70)

I have a little confuse, seems you are using two different keys for `seahash::hash` and `seahash::SeaHasher`, it cause we got two different hash values when use different methods

```rust
use std::hash::{Hash, Hasher};

use fasthash::{sea, SeaHasher};

fn hash<T: Hash>(t: &T) -> u64 {
    let mut s = SeaHasher::new();
    t.hash(&mut s);
    s.finish()
}

assert_eq!(sea::hash64(b"hello world\xff"), 8985868041853666652);

assert_eq!(hash(&"hello world"), 1198299633807023012);
```
Consider the other hash function with the stream mode,`Spooky`, `xxHash` etc., all of those give same hash value as we normally expected.

On the other hand, you may like to check the [t1ha](https://github.com/rurban/smhasher/blob/master/doc/t1ha) hash.

```
test bench_sea_hash_key_128            ... bench:      20,329 ns/iter (+/- 4,360) = 6296 MB/s
test bench_sea_hash_key_16             ... bench:       8,151 ns/iter (+/- 1,072) = 1962 MB/s
test bench_sea_hash_key_256            ... bench:      35,235 ns/iter (+/- 4,169) = 7265 MB/s
test bench_sea_hash_key_32             ... bench:       9,364 ns/iter (+/- 925) = 3417 MB/s
test bench_sea_hash_key_512            ... bench:      62,414 ns/iter (+/- 5,262) = 8203 MB/s
test bench_sea_hash_key_64             ... bench:      12,897 ns/iter (+/- 1,207) = 4962 MB/s
```
It could achieve an impressive throughput with or without SSE 4.2 CRC instruct.
```
test bench_t1ha64_crc_key_128          ... bench:      13,094 ns/iter (+/- 1,136) = 9775 MB/s
test bench_t1ha64_crc_key_16           ... bench:       5,944 ns/iter (+/- 2,654) = 2691 MB/s
test bench_t1ha64_crc_key_256          ... bench:      20,357 ns/iter (+/- 2,140) = 12575 MB/s
test bench_t1ha64_crc_key_32           ... bench:       6,510 ns/iter (+/- 4,260) = 4915 MB/s
test bench_t1ha64_crc_key_512          ... bench:      34,703 ns/iter (+/- 18,593) = 14753 MB/s
test bench_t1ha64_crc_key_64           ... bench:      10,513 ns/iter (+/- 1,134) = 6087 MB/s
```
```
test bench_t1ha64_le_key_128           ... bench:      16,193 ns/iter (+/- 1,858) = 7904 MB/s
test bench_t1ha64_le_key_16            ... bench:       5,662 ns/iter (+/- 772) = 2825 MB/s
test bench_t1ha64_le_key_256           ... bench:      25,355 ns/iter (+/- 10,863) = 10096 MB/s
test bench_t1ha64_le_key_32            ... bench:       6,883 ns/iter (+/- 2,988) = 4649 MB/s
test bench_t1ha64_le_key_512           ... bench:      43,156 ns/iter (+/- 4,204) = 11863 MB/s
test bench_t1ha64_le_key_64            ... bench:      11,503 ns/iter (+/- 826) = 5563 MB/s
```

**Comment by NoraCodes** [comment]
I have spent some time benchmarking various hash functions and have found a rather odd discrepancy with this Sea implementation. Here you can see a plot of the latency for a particular hashing workload using the SeaHash 4 and FastHash 0.4 implementations with their respective Hasher impls (C) or my proxy Hasher impl (P).

![fasthash_seahash_wtf](https://user-images.githubusercontent.com/3290365/148840639-7809bf11-c1f5-4207-871c-5b06e46a2dc4.png)

I'm not too bothered about the consistency here because I'm not using a clean machine for this benchmarking, but I _am_ interested in why the `fasthash` implementation is about 15% faster than the `seahash` implementation. In addition, I'm concerned because they do not produce identical outputs; for instance, for the u64 `0xdeadbeef_u64`, this implementation produces 13029870898238459914 while the official crate produces `8423883450048233688`. (see [this gist](https://gist.github.com/NoraCodes/d2f553e3f34fdae4f4d275649c092122)) 

Looking at the streaming implementation with `Hasher`, it looks like this crate is doing some very different operations than is the `seahash` impl, and I'm curious as to why.

**Comment by ibotty** [comment]
I also noticed strange phenomena with `\0` bytes.
`seahash::hash(b"\01")` and `fasthash::sea::hash64(b"\01")` produce the same different output than the python implementation in https://pypi.org/project/seahash/ using `import seahash; seahash.hash(b"\01")`.

For a portable hash function this does not look nice.
